# Generated by Django 2.0.5 on 2018-05-10 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20180510_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-created']},
        ),
    ]
