# Generated by Django 2.0.5 on 2018-05-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('bw_image', models.ImageField(upload_to='bw/')),
                ('color_image', models.ImageField(upload_to='color/')),
                ('original_image', models.ImageField(upload_to='original/')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
