# Generated by Django 2.0.2 on 2018-03-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='base64',
            new_name='base64_bw',
        ),
        migrations.AddField(
            model_name='image',
            name='base64_color',
            field=models.TextField(blank=True, default=''),
        ),
    ]
