# Generated by Django 2.0.5 on 2018-05-10 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20180508_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageconversion',
            options={'ordering': ['created']},
        ),
    ]
