# Generated by Django 2.0.5 on 2018-05-08 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='following',
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
